import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

/* Geist Font */
const geist = Geist({
  subsets: ["latin"],
  weight: ["300", "500"], // light, medium
  variable: "--font-geist",
});

/* Inter Font */
const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"], // light, regular, medium, semibold
  variable: "--font-inter",
});

/* Geist Font */
// const geist = localFont({
//   src: [
//     { path: "../public/fonts/geist-v4-latin-300.woff2", weight: "300", style: "normal" },
//     { path: "../public/fonts/geist-v4-latin-500.woff2", weight: "500", style: "normal" }
//   ],
//   variable: "--font-geist",
// });

// /* Inter Font */
// const inter = localFont({
//   src: [
//     { path: "../public/fonts/inter-v20-latin-regular.woff2", weight: "400", style: "normal" }, 
//     { path: "../public/fonts/inter-v20-latin-300.woff2", weight: "300", style: "normal" },
//     { path: "../public/fonts/inter-v20-latin-500.woff2", weight: "500", style: "normal" },
//     { path: "../public/fonts/inter-v20-latin-600.woff2", weight: "600", style: "normal" }
//   ],
//   variable: "--font-inter",
// });

export const metadata: Metadata = {
  title: "Letty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geist.variable} ${inter.variable} antialiased`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
